services:
    database:
        container_name: plc-mysql
        image: biarms/mysql:5
#        ports:
#            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_DATABASE=scadalts
        expose: ["3306"]
        volumes:
            - volume_data:/var/lib/mysql/
        restart: always
        healthcheck:
            test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
            timeout: 20s
            retries: 10


    openplc:
        container_name: plc-openplc
        image: openplc:v3
        build: ./OpenPLC_v3
        expose:
            - "8080"
            - "502"
        devices:
            - "/dev/ttySC0"
        restart: always
        volumes:
            - volume_openplc:/persistent/


    scadalts:
        container_name: plc-scada
        image: scadalts/scadalts:latest
        depends_on:
            database:
              condition: service_healthy
            openplc:
              condition: service_started
        expose: ["8080", "8000"]
        links:
            - database:database
        restart: always


    reverse_proxy:
        container_name: plc-proxy
        image: caddy:alpine
        restart: always
        depends_on:
            - openplc
            - scadalts
        ports:
            - 80:80
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile:ro,z
volumes:
    volume_openplc:
      external: true
    volume_data:
      external: true

